[package]
name = "unifed-flower"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "Integrating Flower framework into UniFed as a CoLink protocol."
language = "python"
install_script = """
if { conda env list | grep 'colink-protocol-unifed-flower'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-flower
fi
conda create -n colink-protocol-unifed-flower python=3.9 -y
conda activate colink-protocol-unifed-flower
git clone https://github.com/adap/flower.git
cd flower
cd ..
"""
entrypoint = """
conda activate colink-protocol-unifed-flower
"""
